# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.7
#
# <auto-generated>
#
# Generated from file `iceflix.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module IceFlix
_M_IceFlix = Ice.openModule('IceFlix')
__name__ = 'IceFlix'

if 'Unauthorized' not in _M_IceFlix.__dict__:
    _M_IceFlix.Unauthorized = Ice.createTempClass()
    class Unauthorized(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IceFlix::Unauthorized'

    _M_IceFlix._t_Unauthorized = IcePy.defineException('::IceFlix::Unauthorized', Unauthorized, (), False, None, ())
    Unauthorized._ice_type = _M_IceFlix._t_Unauthorized

    _M_IceFlix.Unauthorized = Unauthorized
    del Unauthorized

if 'WrongMediaId' not in _M_IceFlix.__dict__:
    _M_IceFlix.WrongMediaId = Ice.createTempClass()
    class WrongMediaId(Ice.UserException):
        def __init__(self, mediaId=''):
            self.mediaId = mediaId

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IceFlix::WrongMediaId'

    _M_IceFlix._t_WrongMediaId = IcePy.defineException('::IceFlix::WrongMediaId', WrongMediaId, (), False, None, (('mediaId', (), IcePy._t_string, False, 0),))
    WrongMediaId._ice_type = _M_IceFlix._t_WrongMediaId

    _M_IceFlix.WrongMediaId = WrongMediaId
    del WrongMediaId

if 'TemporaryUnavailable' not in _M_IceFlix.__dict__:
    _M_IceFlix.TemporaryUnavailable = Ice.createTempClass()
    class TemporaryUnavailable(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IceFlix::TemporaryUnavailable'

    _M_IceFlix._t_TemporaryUnavailable = IcePy.defineException('::IceFlix::TemporaryUnavailable', TemporaryUnavailable, (), False, None, ())
    TemporaryUnavailable._ice_type = _M_IceFlix._t_TemporaryUnavailable

    _M_IceFlix.TemporaryUnavailable = TemporaryUnavailable
    del TemporaryUnavailable

if 'UploadError' not in _M_IceFlix.__dict__:
    _M_IceFlix.UploadError = Ice.createTempClass()
    class UploadError(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IceFlix::UploadError'

    _M_IceFlix._t_UploadError = IcePy.defineException('::IceFlix::UploadError', UploadError, (), False, None, ())
    UploadError._ice_type = _M_IceFlix._t_UploadError

    _M_IceFlix.UploadError = UploadError
    del UploadError

if 'UnknownService' not in _M_IceFlix.__dict__:
    _M_IceFlix.UnknownService = Ice.createTempClass()
    class UnknownService(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IceFlix::UnknownService'

    _M_IceFlix._t_UnknownService = IcePy.defineException('::IceFlix::UnknownService', UnknownService, (), False, None, ())
    UnknownService._ice_type = _M_IceFlix._t_UnknownService

    _M_IceFlix.UnknownService = UnknownService
    del UnknownService

_M_IceFlix._t_StreamController = IcePy.defineValue('::IceFlix::StreamController', Ice.Value, -1, (), False, True, None, ())

if 'StreamControllerPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.StreamControllerPrx = Ice.createTempClass()
    class StreamControllerPrx(Ice.ObjectPrx):

        def getSDP(self, userToken, port, context=None):
            return _M_IceFlix.StreamController._op_getSDP.invoke(self, ((userToken, port), context))

        def getSDPAsync(self, userToken, port, context=None):
            return _M_IceFlix.StreamController._op_getSDP.invokeAsync(self, ((userToken, port), context))

        def begin_getSDP(self, userToken, port, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamController._op_getSDP.begin(self, ((userToken, port), _response, _ex, _sent, context))

        def end_getSDP(self, _r):
            return _M_IceFlix.StreamController._op_getSDP.end(self, _r)

        def getSyncTopic(self, context=None):
            return _M_IceFlix.StreamController._op_getSyncTopic.invoke(self, ((), context))

        def getSyncTopicAsync(self, context=None):
            return _M_IceFlix.StreamController._op_getSyncTopic.invokeAsync(self, ((), context))

        def begin_getSyncTopic(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamController._op_getSyncTopic.begin(self, ((), _response, _ex, _sent, context))

        def end_getSyncTopic(self, _r):
            return _M_IceFlix.StreamController._op_getSyncTopic.end(self, _r)

        def refreshAuthentication(self, userToken, context=None):
            return _M_IceFlix.StreamController._op_refreshAuthentication.invoke(self, ((userToken, ), context))

        def refreshAuthenticationAsync(self, userToken, context=None):
            return _M_IceFlix.StreamController._op_refreshAuthentication.invokeAsync(self, ((userToken, ), context))

        def begin_refreshAuthentication(self, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamController._op_refreshAuthentication.begin(self, ((userToken, ), _response, _ex, _sent, context))

        def end_refreshAuthentication(self, _r):
            return _M_IceFlix.StreamController._op_refreshAuthentication.end(self, _r)

        def stop(self, context=None):
            return _M_IceFlix.StreamController._op_stop.invoke(self, ((), context))

        def stopAsync(self, context=None):
            return _M_IceFlix.StreamController._op_stop.invokeAsync(self, ((), context))

        def begin_stop(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamController._op_stop.begin(self, ((), _response, _ex, _sent, context))

        def end_stop(self, _r):
            return _M_IceFlix.StreamController._op_stop.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.StreamControllerPrx.ice_checkedCast(proxy, '::IceFlix::StreamController', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.StreamControllerPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamController'
    _M_IceFlix._t_StreamControllerPrx = IcePy.defineProxy('::IceFlix::StreamController', StreamControllerPrx)

    _M_IceFlix.StreamControllerPrx = StreamControllerPrx
    del StreamControllerPrx

    _M_IceFlix.StreamController = Ice.createTempClass()
    class StreamController(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::StreamController')

        def ice_id(self, current=None):
            return '::IceFlix::StreamController'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamController'

        def getSDP(self, userToken, port, current=None):
            raise NotImplementedError("servant method 'getSDP' not implemented")

        def getSyncTopic(self, current=None):
            raise NotImplementedError("servant method 'getSyncTopic' not implemented")

        def refreshAuthentication(self, userToken, current=None):
            raise NotImplementedError("servant method 'refreshAuthentication' not implemented")

        def stop(self, current=None):
            raise NotImplementedError("servant method 'stop' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_StreamControllerDisp)

        __repr__ = __str__

    _M_IceFlix._t_StreamControllerDisp = IcePy.defineClass('::IceFlix::StreamController', StreamController, (), None, ())
    StreamController._ice_type = _M_IceFlix._t_StreamControllerDisp

    StreamController._op_getSDP = IcePy.Operation('getSDP', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_int, False, 0)), (), ((), IcePy._t_string, False, 0), (_M_IceFlix._t_Unauthorized,))
    StreamController._op_getSyncTopic = IcePy.Operation('getSyncTopic', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_string, False, 0), ())
    StreamController._op_refreshAuthentication = IcePy.Operation('refreshAuthentication', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, (_M_IceFlix._t_Unauthorized,))
    StreamController._op_stop = IcePy.Operation('stop', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_IceFlix.StreamController = StreamController
    del StreamController

_M_IceFlix._t_StreamSync = IcePy.defineValue('::IceFlix::StreamSync', Ice.Value, -1, (), False, True, None, ())

if 'StreamSyncPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.StreamSyncPrx = Ice.createTempClass()
    class StreamSyncPrx(Ice.ObjectPrx):

        def requestAuthentication(self, context=None):
            return _M_IceFlix.StreamSync._op_requestAuthentication.invoke(self, ((), context))

        def requestAuthenticationAsync(self, context=None):
            return _M_IceFlix.StreamSync._op_requestAuthentication.invokeAsync(self, ((), context))

        def begin_requestAuthentication(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamSync._op_requestAuthentication.begin(self, ((), _response, _ex, _sent, context))

        def end_requestAuthentication(self, _r):
            return _M_IceFlix.StreamSync._op_requestAuthentication.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.StreamSyncPrx.ice_checkedCast(proxy, '::IceFlix::StreamSync', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.StreamSyncPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamSync'
    _M_IceFlix._t_StreamSyncPrx = IcePy.defineProxy('::IceFlix::StreamSync', StreamSyncPrx)

    _M_IceFlix.StreamSyncPrx = StreamSyncPrx
    del StreamSyncPrx

    _M_IceFlix.StreamSync = Ice.createTempClass()
    class StreamSync(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::StreamSync')

        def ice_id(self, current=None):
            return '::IceFlix::StreamSync'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamSync'

        def requestAuthentication(self, current=None):
            raise NotImplementedError("servant method 'requestAuthentication' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_StreamSyncDisp)

        __repr__ = __str__

    _M_IceFlix._t_StreamSyncDisp = IcePy.defineClass('::IceFlix::StreamSync', StreamSync, (), None, ())
    StreamSync._ice_type = _M_IceFlix._t_StreamSyncDisp

    StreamSync._op_requestAuthentication = IcePy.Operation('requestAuthentication', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_IceFlix.StreamSync = StreamSync
    del StreamSync

if '_t_Bytes' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_Bytes = IcePy.defineSequence('::IceFlix::Bytes', (), IcePy._t_byte)

_M_IceFlix._t_MediaUploader = IcePy.defineValue('::IceFlix::MediaUploader', Ice.Value, -1, (), False, True, None, ())

if 'MediaUploaderPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.MediaUploaderPrx = Ice.createTempClass()
    class MediaUploaderPrx(Ice.ObjectPrx):

        def receive(self, size, context=None):
            return _M_IceFlix.MediaUploader._op_receive.invoke(self, ((size, ), context))

        def receiveAsync(self, size, context=None):
            return _M_IceFlix.MediaUploader._op_receive.invokeAsync(self, ((size, ), context))

        def begin_receive(self, size, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaUploader._op_receive.begin(self, ((size, ), _response, _ex, _sent, context))

        def end_receive(self, _r):
            return _M_IceFlix.MediaUploader._op_receive.end(self, _r)

        def close(self, context=None):
            return _M_IceFlix.MediaUploader._op_close.invoke(self, ((), context))

        def closeAsync(self, context=None):
            return _M_IceFlix.MediaUploader._op_close.invokeAsync(self, ((), context))

        def begin_close(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaUploader._op_close.begin(self, ((), _response, _ex, _sent, context))

        def end_close(self, _r):
            return _M_IceFlix.MediaUploader._op_close.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.MediaUploaderPrx.ice_checkedCast(proxy, '::IceFlix::MediaUploader', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.MediaUploaderPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::MediaUploader'
    _M_IceFlix._t_MediaUploaderPrx = IcePy.defineProxy('::IceFlix::MediaUploader', MediaUploaderPrx)

    _M_IceFlix.MediaUploaderPrx = MediaUploaderPrx
    del MediaUploaderPrx

    _M_IceFlix.MediaUploader = Ice.createTempClass()
    class MediaUploader(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::MediaUploader')

        def ice_id(self, current=None):
            return '::IceFlix::MediaUploader'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::MediaUploader'

        def receive(self, size, current=None):
            raise NotImplementedError("servant method 'receive' not implemented")

        def close(self, current=None):
            raise NotImplementedError("servant method 'close' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_MediaUploaderDisp)

        __repr__ = __str__

    _M_IceFlix._t_MediaUploaderDisp = IcePy.defineClass('::IceFlix::MediaUploader', MediaUploader, (), None, ())
    MediaUploader._ice_type = _M_IceFlix._t_MediaUploaderDisp

    MediaUploader._op_receive = IcePy.Operation('receive', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_int, False, 0),), (), ((), _M_IceFlix._t_Bytes, False, 0), ())
    MediaUploader._op_close = IcePy.Operation('close', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_IceFlix.MediaUploader = MediaUploader
    del MediaUploader

_M_IceFlix._t_StreamProvider = IcePy.defineValue('::IceFlix::StreamProvider', Ice.Value, -1, (), False, True, None, ())

if 'StreamProviderPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.StreamProviderPrx = Ice.createTempClass()
    class StreamProviderPrx(Ice.ObjectPrx):

        def getStream(self, mediaId, userToken, context=None):
            return _M_IceFlix.StreamProvider._op_getStream.invoke(self, ((mediaId, userToken), context))

        def getStreamAsync(self, mediaId, userToken, context=None):
            return _M_IceFlix.StreamProvider._op_getStream.invokeAsync(self, ((mediaId, userToken), context))

        def begin_getStream(self, mediaId, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamProvider._op_getStream.begin(self, ((mediaId, userToken), _response, _ex, _sent, context))

        def end_getStream(self, _r):
            return _M_IceFlix.StreamProvider._op_getStream.end(self, _r)

        def isAvailable(self, mediaId, context=None):
            return _M_IceFlix.StreamProvider._op_isAvailable.invoke(self, ((mediaId, ), context))

        def isAvailableAsync(self, mediaId, context=None):
            return _M_IceFlix.StreamProvider._op_isAvailable.invokeAsync(self, ((mediaId, ), context))

        def begin_isAvailable(self, mediaId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamProvider._op_isAvailable.begin(self, ((mediaId, ), _response, _ex, _sent, context))

        def end_isAvailable(self, _r):
            return _M_IceFlix.StreamProvider._op_isAvailable.end(self, _r)

        def reannounceMedia(self, srvId, context=None):
            return _M_IceFlix.StreamProvider._op_reannounceMedia.invoke(self, ((srvId, ), context))

        def reannounceMediaAsync(self, srvId, context=None):
            return _M_IceFlix.StreamProvider._op_reannounceMedia.invokeAsync(self, ((srvId, ), context))

        def begin_reannounceMedia(self, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamProvider._op_reannounceMedia.begin(self, ((srvId, ), _response, _ex, _sent, context))

        def end_reannounceMedia(self, _r):
            return _M_IceFlix.StreamProvider._op_reannounceMedia.end(self, _r)

        def uploadMedia(self, fileName, uploader, adminToken, context=None):
            return _M_IceFlix.StreamProvider._op_uploadMedia.invoke(self, ((fileName, uploader, adminToken), context))

        def uploadMediaAsync(self, fileName, uploader, adminToken, context=None):
            return _M_IceFlix.StreamProvider._op_uploadMedia.invokeAsync(self, ((fileName, uploader, adminToken), context))

        def begin_uploadMedia(self, fileName, uploader, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamProvider._op_uploadMedia.begin(self, ((fileName, uploader, adminToken), _response, _ex, _sent, context))

        def end_uploadMedia(self, _r):
            return _M_IceFlix.StreamProvider._op_uploadMedia.end(self, _r)

        def deleteMedia(self, mediaId, adminToken, context=None):
            return _M_IceFlix.StreamProvider._op_deleteMedia.invoke(self, ((mediaId, adminToken), context))

        def deleteMediaAsync(self, mediaId, adminToken, context=None):
            return _M_IceFlix.StreamProvider._op_deleteMedia.invokeAsync(self, ((mediaId, adminToken), context))

        def begin_deleteMedia(self, mediaId, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamProvider._op_deleteMedia.begin(self, ((mediaId, adminToken), _response, _ex, _sent, context))

        def end_deleteMedia(self, _r):
            return _M_IceFlix.StreamProvider._op_deleteMedia.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.StreamProviderPrx.ice_checkedCast(proxy, '::IceFlix::StreamProvider', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.StreamProviderPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamProvider'
    _M_IceFlix._t_StreamProviderPrx = IcePy.defineProxy('::IceFlix::StreamProvider', StreamProviderPrx)

    _M_IceFlix.StreamProviderPrx = StreamProviderPrx
    del StreamProviderPrx

    _M_IceFlix.StreamProvider = Ice.createTempClass()
    class StreamProvider(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::StreamProvider')

        def ice_id(self, current=None):
            return '::IceFlix::StreamProvider'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamProvider'

        def getStream(self, mediaId, userToken, current=None):
            raise NotImplementedError("servant method 'getStream' not implemented")

        def isAvailable(self, mediaId, current=None):
            raise NotImplementedError("servant method 'isAvailable' not implemented")

        def reannounceMedia(self, srvId, current=None):
            raise NotImplementedError("servant method 'reannounceMedia' not implemented")

        def uploadMedia(self, fileName, uploader, adminToken, current=None):
            raise NotImplementedError("servant method 'uploadMedia' not implemented")

        def deleteMedia(self, mediaId, adminToken, current=None):
            raise NotImplementedError("servant method 'deleteMedia' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_StreamProviderDisp)

        __repr__ = __str__

    _M_IceFlix._t_StreamProviderDisp = IcePy.defineClass('::IceFlix::StreamProvider', StreamProvider, (), None, ())
    StreamProvider._ice_type = _M_IceFlix._t_StreamProviderDisp

    StreamProvider._op_getStream = IcePy.Operation('getStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), _M_IceFlix._t_StreamControllerPrx, False, 0), (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_WrongMediaId))
    StreamProvider._op_isAvailable = IcePy.Operation('isAvailable', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_bool, False, 0), ())
    StreamProvider._op_reannounceMedia = IcePy.Operation('reannounceMedia', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, (_M_IceFlix._t_UnknownService,))
    StreamProvider._op_uploadMedia = IcePy.Operation('uploadMedia', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IceFlix._t_MediaUploaderPrx, False, 0), ((), IcePy._t_string, False, 0)), (), ((), IcePy._t_string, False, 0), (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_UploadError))
    StreamProvider._op_deleteMedia = IcePy.Operation('deleteMedia', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_WrongMediaId))

    _M_IceFlix.StreamProvider = StreamProvider
    del StreamProvider

_M_IceFlix._t_StreamAnnouncements = IcePy.defineValue('::IceFlix::StreamAnnouncements', Ice.Value, -1, (), False, True, None, ())

if 'StreamAnnouncementsPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.StreamAnnouncementsPrx = Ice.createTempClass()
    class StreamAnnouncementsPrx(Ice.ObjectPrx):

        def newMedia(self, mediaId, initialName, srvId, context=None):
            return _M_IceFlix.StreamAnnouncements._op_newMedia.invoke(self, ((mediaId, initialName, srvId), context))

        def newMediaAsync(self, mediaId, initialName, srvId, context=None):
            return _M_IceFlix.StreamAnnouncements._op_newMedia.invokeAsync(self, ((mediaId, initialName, srvId), context))

        def begin_newMedia(self, mediaId, initialName, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamAnnouncements._op_newMedia.begin(self, ((mediaId, initialName, srvId), _response, _ex, _sent, context))

        def end_newMedia(self, _r):
            return _M_IceFlix.StreamAnnouncements._op_newMedia.end(self, _r)

        def removedMedia(self, mediaId, srvId, context=None):
            return _M_IceFlix.StreamAnnouncements._op_removedMedia.invoke(self, ((mediaId, srvId), context))

        def removedMediaAsync(self, mediaId, srvId, context=None):
            return _M_IceFlix.StreamAnnouncements._op_removedMedia.invokeAsync(self, ((mediaId, srvId), context))

        def begin_removedMedia(self, mediaId, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.StreamAnnouncements._op_removedMedia.begin(self, ((mediaId, srvId), _response, _ex, _sent, context))

        def end_removedMedia(self, _r):
            return _M_IceFlix.StreamAnnouncements._op_removedMedia.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.StreamAnnouncementsPrx.ice_checkedCast(proxy, '::IceFlix::StreamAnnouncements', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.StreamAnnouncementsPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamAnnouncements'
    _M_IceFlix._t_StreamAnnouncementsPrx = IcePy.defineProxy('::IceFlix::StreamAnnouncements', StreamAnnouncementsPrx)

    _M_IceFlix.StreamAnnouncementsPrx = StreamAnnouncementsPrx
    del StreamAnnouncementsPrx

    _M_IceFlix.StreamAnnouncements = Ice.createTempClass()
    class StreamAnnouncements(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::StreamAnnouncements')

        def ice_id(self, current=None):
            return '::IceFlix::StreamAnnouncements'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::StreamAnnouncements'

        def newMedia(self, mediaId, initialName, srvId, current=None):
            raise NotImplementedError("servant method 'newMedia' not implemented")

        def removedMedia(self, mediaId, srvId, current=None):
            raise NotImplementedError("servant method 'removedMedia' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_StreamAnnouncementsDisp)

        __repr__ = __str__

    _M_IceFlix._t_StreamAnnouncementsDisp = IcePy.defineClass('::IceFlix::StreamAnnouncements', StreamAnnouncements, (), None, ())
    StreamAnnouncements._ice_type = _M_IceFlix._t_StreamAnnouncementsDisp

    StreamAnnouncements._op_newMedia = IcePy.Operation('newMedia', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    StreamAnnouncements._op_removedMedia = IcePy.Operation('removedMedia', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_IceFlix.StreamAnnouncements = StreamAnnouncements
    del StreamAnnouncements

if '_t_StringList' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_StringList = IcePy.defineSequence('::IceFlix::StringList', (), IcePy._t_string)

if 'MediaInfo' not in _M_IceFlix.__dict__:
    _M_IceFlix.MediaInfo = Ice.createTempClass()
    class MediaInfo(object):
        def __init__(self, name='', tags=None):
            self.name = name
            self.tags = tags

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.name)
            if self.tags:
                for _i0 in self.tags:
                    _h = 5 * _h + Ice.getHash(_i0)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_IceFlix.MediaInfo):
                return NotImplemented
            else:
                if self.name is None or other.name is None:
                    if self.name != other.name:
                        return (-1 if self.name is None else 1)
                else:
                    if self.name < other.name:
                        return -1
                    elif self.name > other.name:
                        return 1
                if self.tags is None or other.tags is None:
                    if self.tags != other.tags:
                        return (-1 if self.tags is None else 1)
                else:
                    if self.tags < other.tags:
                        return -1
                    elif self.tags > other.tags:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_MediaInfo)

        __repr__ = __str__

    _M_IceFlix._t_MediaInfo = IcePy.defineStruct('::IceFlix::MediaInfo', MediaInfo, (), (
        ('name', (), IcePy._t_string),
        ('tags', (), _M_IceFlix._t_StringList)
    ))

    _M_IceFlix.MediaInfo = MediaInfo
    del MediaInfo

if 'Media' not in _M_IceFlix.__dict__:
    _M_IceFlix.Media = Ice.createTempClass()
    class Media(object):
        def __init__(self, mediaId='', provider=None, info=Ice._struct_marker):
            self.mediaId = mediaId
            self.provider = provider
            if info is Ice._struct_marker:
                self.info = _M_IceFlix.MediaInfo()
            else:
                self.info = info

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IceFlix.Media):
                return NotImplemented
            else:
                if self.mediaId != other.mediaId:
                    return False
                if self.provider != other.provider:
                    return False
                if self.info != other.info:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_Media)

        __repr__ = __str__

    _M_IceFlix._t_Media = IcePy.defineStruct('::IceFlix::Media', Media, (), (
        ('mediaId', (), IcePy._t_string),
        ('provider', (), _M_IceFlix._t_StreamProviderPrx),
        ('info', (), _M_IceFlix._t_MediaInfo)
    ))

    _M_IceFlix.Media = Media
    del Media

if '_t_TagsPerUser' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_TagsPerUser = IcePy.defineDictionary('::IceFlix::TagsPerUser', (), IcePy._t_string, _M_IceFlix._t_StringList)

if 'MediaDB' not in _M_IceFlix.__dict__:
    _M_IceFlix.MediaDB = Ice.createTempClass()
    class MediaDB(object):
        def __init__(self, mediaId='', name='', tagsPerUser=None):
            self.mediaId = mediaId
            self.name = name
            self.tagsPerUser = tagsPerUser

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IceFlix.MediaDB):
                return NotImplemented
            else:
                if self.mediaId != other.mediaId:
                    return False
                if self.name != other.name:
                    return False
                if self.tagsPerUser != other.tagsPerUser:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_MediaDB)

        __repr__ = __str__

    _M_IceFlix._t_MediaDB = IcePy.defineStruct('::IceFlix::MediaDB', MediaDB, (), (
        ('mediaId', (), IcePy._t_string),
        ('name', (), IcePy._t_string),
        ('tagsPerUser', (), _M_IceFlix._t_TagsPerUser)
    ))

    _M_IceFlix.MediaDB = MediaDB
    del MediaDB

if '_t_MediaDBList' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_MediaDBList = IcePy.defineSequence('::IceFlix::MediaDBList', (), _M_IceFlix._t_MediaDB)

_M_IceFlix._t_MediaCatalog = IcePy.defineValue('::IceFlix::MediaCatalog', Ice.Value, -1, (), False, True, None, ())

if 'MediaCatalogPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.MediaCatalogPrx = Ice.createTempClass()
    class MediaCatalogPrx(Ice.ObjectPrx):

        def getTile(self, mediaId, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_getTile.invoke(self, ((mediaId, userToken), context))

        def getTileAsync(self, mediaId, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_getTile.invokeAsync(self, ((mediaId, userToken), context))

        def begin_getTile(self, mediaId, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_getTile.begin(self, ((mediaId, userToken), _response, _ex, _sent, context))

        def end_getTile(self, _r):
            return _M_IceFlix.MediaCatalog._op_getTile.end(self, _r)

        def getTilesByName(self, name, exact, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByName.invoke(self, ((name, exact), context))

        def getTilesByNameAsync(self, name, exact, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByName.invokeAsync(self, ((name, exact), context))

        def begin_getTilesByName(self, name, exact, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByName.begin(self, ((name, exact), _response, _ex, _sent, context))

        def end_getTilesByName(self, _r):
            return _M_IceFlix.MediaCatalog._op_getTilesByName.end(self, _r)

        def getTilesByTags(self, tags, includeAllTags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByTags.invoke(self, ((tags, includeAllTags, userToken), context))

        def getTilesByTagsAsync(self, tags, includeAllTags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByTags.invokeAsync(self, ((tags, includeAllTags, userToken), context))

        def begin_getTilesByTags(self, tags, includeAllTags, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_getTilesByTags.begin(self, ((tags, includeAllTags, userToken), _response, _ex, _sent, context))

        def end_getTilesByTags(self, _r):
            return _M_IceFlix.MediaCatalog._op_getTilesByTags.end(self, _r)

        def addTags(self, mediaId, tags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_addTags.invoke(self, ((mediaId, tags, userToken), context))

        def addTagsAsync(self, mediaId, tags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_addTags.invokeAsync(self, ((mediaId, tags, userToken), context))

        def begin_addTags(self, mediaId, tags, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_addTags.begin(self, ((mediaId, tags, userToken), _response, _ex, _sent, context))

        def end_addTags(self, _r):
            return _M_IceFlix.MediaCatalog._op_addTags.end(self, _r)

        def removeTags(self, mediaId, tags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_removeTags.invoke(self, ((mediaId, tags, userToken), context))

        def removeTagsAsync(self, mediaId, tags, userToken, context=None):
            return _M_IceFlix.MediaCatalog._op_removeTags.invokeAsync(self, ((mediaId, tags, userToken), context))

        def begin_removeTags(self, mediaId, tags, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_removeTags.begin(self, ((mediaId, tags, userToken), _response, _ex, _sent, context))

        def end_removeTags(self, _r):
            return _M_IceFlix.MediaCatalog._op_removeTags.end(self, _r)

        def renameTile(self, mediaId, name, adminToken, context=None):
            return _M_IceFlix.MediaCatalog._op_renameTile.invoke(self, ((mediaId, name, adminToken), context))

        def renameTileAsync(self, mediaId, name, adminToken, context=None):
            return _M_IceFlix.MediaCatalog._op_renameTile.invokeAsync(self, ((mediaId, name, adminToken), context))

        def begin_renameTile(self, mediaId, name, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_renameTile.begin(self, ((mediaId, name, adminToken), _response, _ex, _sent, context))

        def end_renameTile(self, _r):
            return _M_IceFlix.MediaCatalog._op_renameTile.end(self, _r)

        def updateDB(self, catalogDatabase, srvId, context=None):
            return _M_IceFlix.MediaCatalog._op_updateDB.invoke(self, ((catalogDatabase, srvId), context))

        def updateDBAsync(self, catalogDatabase, srvId, context=None):
            return _M_IceFlix.MediaCatalog._op_updateDB.invokeAsync(self, ((catalogDatabase, srvId), context))

        def begin_updateDB(self, catalogDatabase, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.MediaCatalog._op_updateDB.begin(self, ((catalogDatabase, srvId), _response, _ex, _sent, context))

        def end_updateDB(self, _r):
            return _M_IceFlix.MediaCatalog._op_updateDB.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.MediaCatalogPrx.ice_checkedCast(proxy, '::IceFlix::MediaCatalog', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.MediaCatalogPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::MediaCatalog'
    _M_IceFlix._t_MediaCatalogPrx = IcePy.defineProxy('::IceFlix::MediaCatalog', MediaCatalogPrx)

    _M_IceFlix.MediaCatalogPrx = MediaCatalogPrx
    del MediaCatalogPrx

    _M_IceFlix.MediaCatalog = Ice.createTempClass()
    class MediaCatalog(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::MediaCatalog')

        def ice_id(self, current=None):
            return '::IceFlix::MediaCatalog'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::MediaCatalog'

        def getTile(self, mediaId, userToken, current=None):
            raise NotImplementedError("servant method 'getTile' not implemented")

        def getTilesByName(self, name, exact, current=None):
            raise NotImplementedError("servant method 'getTilesByName' not implemented")

        def getTilesByTags(self, tags, includeAllTags, userToken, current=None):
            raise NotImplementedError("servant method 'getTilesByTags' not implemented")

        def addTags(self, mediaId, tags, userToken, current=None):
            raise NotImplementedError("servant method 'addTags' not implemented")

        def removeTags(self, mediaId, tags, userToken, current=None):
            raise NotImplementedError("servant method 'removeTags' not implemented")

        def renameTile(self, mediaId, name, adminToken, current=None):
            raise NotImplementedError("servant method 'renameTile' not implemented")

        def updateDB(self, catalogDatabase, srvId, current=None):
            raise NotImplementedError("servant method 'updateDB' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_MediaCatalogDisp)

        __repr__ = __str__

    _M_IceFlix._t_MediaCatalogDisp = IcePy.defineClass('::IceFlix::MediaCatalog', MediaCatalog, (), None, ())
    MediaCatalog._ice_type = _M_IceFlix._t_MediaCatalogDisp

    MediaCatalog._op_getTile = IcePy.Operation('getTile', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), _M_IceFlix._t_Media, False, 0), (_M_IceFlix._t_WrongMediaId, _M_IceFlix._t_TemporaryUnavailable, _M_IceFlix._t_Unauthorized))
    MediaCatalog._op_getTilesByName = IcePy.Operation('getTilesByName', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_bool, False, 0)), (), ((), _M_IceFlix._t_StringList, False, 0), ())
    MediaCatalog._op_getTilesByTags = IcePy.Operation('getTilesByTags', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IceFlix._t_StringList, False, 0), ((), IcePy._t_bool, False, 0), ((), IcePy._t_string, False, 0)), (), ((), _M_IceFlix._t_StringList, False, 0), (_M_IceFlix._t_Unauthorized,))
    MediaCatalog._op_addTags = IcePy.Operation('addTags', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IceFlix._t_StringList, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_WrongMediaId))
    MediaCatalog._op_removeTags = IcePy.Operation('removeTags', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IceFlix._t_StringList, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_WrongMediaId))
    MediaCatalog._op_renameTile = IcePy.Operation('renameTile', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_WrongMediaId))
    MediaCatalog._op_updateDB = IcePy.Operation('updateDB', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IceFlix._t_MediaDBList, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_UnknownService,))

    _M_IceFlix.MediaCatalog = MediaCatalog
    del MediaCatalog

_M_IceFlix._t_CatalogUpdates = IcePy.defineValue('::IceFlix::CatalogUpdates', Ice.Value, -1, (), False, True, None, ())

if 'CatalogUpdatesPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.CatalogUpdatesPrx = Ice.createTempClass()
    class CatalogUpdatesPrx(Ice.ObjectPrx):

        def renameTile(self, mediaId, name, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_renameTile.invoke(self, ((mediaId, name, srvId), context))

        def renameTileAsync(self, mediaId, name, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_renameTile.invokeAsync(self, ((mediaId, name, srvId), context))

        def begin_renameTile(self, mediaId, name, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.CatalogUpdates._op_renameTile.begin(self, ((mediaId, name, srvId), _response, _ex, _sent, context))

        def end_renameTile(self, _r):
            return _M_IceFlix.CatalogUpdates._op_renameTile.end(self, _r)

        def addTags(self, mediaId, tags, user, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_addTags.invoke(self, ((mediaId, tags, user, srvId), context))

        def addTagsAsync(self, mediaId, tags, user, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_addTags.invokeAsync(self, ((mediaId, tags, user, srvId), context))

        def begin_addTags(self, mediaId, tags, user, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.CatalogUpdates._op_addTags.begin(self, ((mediaId, tags, user, srvId), _response, _ex, _sent, context))

        def end_addTags(self, _r):
            return _M_IceFlix.CatalogUpdates._op_addTags.end(self, _r)

        def removeTags(self, mediaId, tags, user, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_removeTags.invoke(self, ((mediaId, tags, user, srvId), context))

        def removeTagsAsync(self, mediaId, tags, user, srvId, context=None):
            return _M_IceFlix.CatalogUpdates._op_removeTags.invokeAsync(self, ((mediaId, tags, user, srvId), context))

        def begin_removeTags(self, mediaId, tags, user, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.CatalogUpdates._op_removeTags.begin(self, ((mediaId, tags, user, srvId), _response, _ex, _sent, context))

        def end_removeTags(self, _r):
            return _M_IceFlix.CatalogUpdates._op_removeTags.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.CatalogUpdatesPrx.ice_checkedCast(proxy, '::IceFlix::CatalogUpdates', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.CatalogUpdatesPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::CatalogUpdates'
    _M_IceFlix._t_CatalogUpdatesPrx = IcePy.defineProxy('::IceFlix::CatalogUpdates', CatalogUpdatesPrx)

    _M_IceFlix.CatalogUpdatesPrx = CatalogUpdatesPrx
    del CatalogUpdatesPrx

    _M_IceFlix.CatalogUpdates = Ice.createTempClass()
    class CatalogUpdates(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::CatalogUpdates')

        def ice_id(self, current=None):
            return '::IceFlix::CatalogUpdates'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::CatalogUpdates'

        def renameTile(self, mediaId, name, srvId, current=None):
            raise NotImplementedError("servant method 'renameTile' not implemented")

        def addTags(self, mediaId, tags, user, srvId, current=None):
            raise NotImplementedError("servant method 'addTags' not implemented")

        def removeTags(self, mediaId, tags, user, srvId, current=None):
            raise NotImplementedError("servant method 'removeTags' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_CatalogUpdatesDisp)

        __repr__ = __str__

    _M_IceFlix._t_CatalogUpdatesDisp = IcePy.defineClass('::IceFlix::CatalogUpdates', CatalogUpdates, (), None, ())
    CatalogUpdates._ice_type = _M_IceFlix._t_CatalogUpdatesDisp

    CatalogUpdates._op_renameTile = IcePy.Operation('renameTile', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    CatalogUpdates._op_addTags = IcePy.Operation('addTags', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IceFlix._t_StringList, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    CatalogUpdates._op_removeTags = IcePy.Operation('removeTags', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IceFlix._t_StringList, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_IceFlix.CatalogUpdates = CatalogUpdates
    del CatalogUpdates

if '_t_UsersPasswords' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_UsersPasswords = IcePy.defineDictionary('::IceFlix::UsersPasswords', (), IcePy._t_string, IcePy._t_string)

if '_t_UsersToken' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_UsersToken = IcePy.defineDictionary('::IceFlix::UsersToken', (), IcePy._t_string, IcePy._t_string)

if 'UsersDB' not in _M_IceFlix.__dict__:
    _M_IceFlix.UsersDB = Ice.createTempClass()
    class UsersDB(object):
        def __init__(self, userPasswords=None, usersToken=None):
            self.userPasswords = userPasswords
            self.usersToken = usersToken

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IceFlix.UsersDB):
                return NotImplemented
            else:
                if self.userPasswords != other.userPasswords:
                    return False
                if self.usersToken != other.usersToken:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_UsersDB)

        __repr__ = __str__

    _M_IceFlix._t_UsersDB = IcePy.defineStruct('::IceFlix::UsersDB', UsersDB, (), (
        ('userPasswords', (), _M_IceFlix._t_UsersPasswords),
        ('usersToken', (), _M_IceFlix._t_UsersToken)
    ))

    _M_IceFlix.UsersDB = UsersDB
    del UsersDB

_M_IceFlix._t_Authenticator = IcePy.defineValue('::IceFlix::Authenticator', Ice.Value, -1, (), False, True, None, ())

if 'AuthenticatorPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.AuthenticatorPrx = Ice.createTempClass()
    class AuthenticatorPrx(Ice.ObjectPrx):

        def refreshAuthorization(self, user, passwordHash, context=None):
            return _M_IceFlix.Authenticator._op_refreshAuthorization.invoke(self, ((user, passwordHash), context))

        def refreshAuthorizationAsync(self, user, passwordHash, context=None):
            return _M_IceFlix.Authenticator._op_refreshAuthorization.invokeAsync(self, ((user, passwordHash), context))

        def begin_refreshAuthorization(self, user, passwordHash, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_refreshAuthorization.begin(self, ((user, passwordHash), _response, _ex, _sent, context))

        def end_refreshAuthorization(self, _r):
            return _M_IceFlix.Authenticator._op_refreshAuthorization.end(self, _r)

        def isAuthorized(self, userToken, context=None):
            return _M_IceFlix.Authenticator._op_isAuthorized.invoke(self, ((userToken, ), context))

        def isAuthorizedAsync(self, userToken, context=None):
            return _M_IceFlix.Authenticator._op_isAuthorized.invokeAsync(self, ((userToken, ), context))

        def begin_isAuthorized(self, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_isAuthorized.begin(self, ((userToken, ), _response, _ex, _sent, context))

        def end_isAuthorized(self, _r):
            return _M_IceFlix.Authenticator._op_isAuthorized.end(self, _r)

        def whois(self, userToken, context=None):
            return _M_IceFlix.Authenticator._op_whois.invoke(self, ((userToken, ), context))

        def whoisAsync(self, userToken, context=None):
            return _M_IceFlix.Authenticator._op_whois.invokeAsync(self, ((userToken, ), context))

        def begin_whois(self, userToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_whois.begin(self, ((userToken, ), _response, _ex, _sent, context))

        def end_whois(self, _r):
            return _M_IceFlix.Authenticator._op_whois.end(self, _r)

        def addUser(self, user, passwordHash, adminToken, context=None):
            return _M_IceFlix.Authenticator._op_addUser.invoke(self, ((user, passwordHash, adminToken), context))

        def addUserAsync(self, user, passwordHash, adminToken, context=None):
            return _M_IceFlix.Authenticator._op_addUser.invokeAsync(self, ((user, passwordHash, adminToken), context))

        def begin_addUser(self, user, passwordHash, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_addUser.begin(self, ((user, passwordHash, adminToken), _response, _ex, _sent, context))

        def end_addUser(self, _r):
            return _M_IceFlix.Authenticator._op_addUser.end(self, _r)

        def removeUser(self, user, adminToken, context=None):
            return _M_IceFlix.Authenticator._op_removeUser.invoke(self, ((user, adminToken), context))

        def removeUserAsync(self, user, adminToken, context=None):
            return _M_IceFlix.Authenticator._op_removeUser.invokeAsync(self, ((user, adminToken), context))

        def begin_removeUser(self, user, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_removeUser.begin(self, ((user, adminToken), _response, _ex, _sent, context))

        def end_removeUser(self, _r):
            return _M_IceFlix.Authenticator._op_removeUser.end(self, _r)

        def updateDB(self, currentDatabase, srvId, context=None):
            return _M_IceFlix.Authenticator._op_updateDB.invoke(self, ((currentDatabase, srvId), context))

        def updateDBAsync(self, currentDatabase, srvId, context=None):
            return _M_IceFlix.Authenticator._op_updateDB.invokeAsync(self, ((currentDatabase, srvId), context))

        def begin_updateDB(self, currentDatabase, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Authenticator._op_updateDB.begin(self, ((currentDatabase, srvId), _response, _ex, _sent, context))

        def end_updateDB(self, _r):
            return _M_IceFlix.Authenticator._op_updateDB.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.AuthenticatorPrx.ice_checkedCast(proxy, '::IceFlix::Authenticator', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.AuthenticatorPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Authenticator'
    _M_IceFlix._t_AuthenticatorPrx = IcePy.defineProxy('::IceFlix::Authenticator', AuthenticatorPrx)

    _M_IceFlix.AuthenticatorPrx = AuthenticatorPrx
    del AuthenticatorPrx

    _M_IceFlix.Authenticator = Ice.createTempClass()
    class Authenticator(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::Authenticator')

        def ice_id(self, current=None):
            return '::IceFlix::Authenticator'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Authenticator'

        def refreshAuthorization(self, user, passwordHash, current=None):
            raise NotImplementedError("servant method 'refreshAuthorization' not implemented")

        def isAuthorized(self, userToken, current=None):
            raise NotImplementedError("servant method 'isAuthorized' not implemented")

        def whois(self, userToken, current=None):
            raise NotImplementedError("servant method 'whois' not implemented")

        def addUser(self, user, passwordHash, adminToken, current=None):
            raise NotImplementedError("servant method 'addUser' not implemented")

        def removeUser(self, user, adminToken, current=None):
            raise NotImplementedError("servant method 'removeUser' not implemented")

        def updateDB(self, currentDatabase, srvId, current=None):
            raise NotImplementedError("servant method 'updateDB' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_AuthenticatorDisp)

        __repr__ = __str__

    _M_IceFlix._t_AuthenticatorDisp = IcePy.defineClass('::IceFlix::Authenticator', Authenticator, (), None, ())
    Authenticator._ice_type = _M_IceFlix._t_AuthenticatorDisp

    Authenticator._op_refreshAuthorization = IcePy.Operation('refreshAuthorization', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), IcePy._t_string, False, 0), (_M_IceFlix._t_Unauthorized,))
    Authenticator._op_isAuthorized = IcePy.Operation('isAuthorized', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_bool, False, 0), ())
    Authenticator._op_whois = IcePy.Operation('whois', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), (_M_IceFlix._t_Unauthorized,))
    Authenticator._op_addUser = IcePy.Operation('addUser', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_TemporaryUnavailable))
    Authenticator._op_removeUser = IcePy.Operation('removeUser', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_Unauthorized, _M_IceFlix._t_TemporaryUnavailable))
    Authenticator._op_updateDB = IcePy.Operation('updateDB', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IceFlix._t_UsersDB, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_UnknownService,))

    _M_IceFlix.Authenticator = Authenticator
    del Authenticator

_M_IceFlix._t_UserUpdates = IcePy.defineValue('::IceFlix::UserUpdates', Ice.Value, -1, (), False, True, None, ())

if 'UserUpdatesPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.UserUpdatesPrx = Ice.createTempClass()
    class UserUpdatesPrx(Ice.ObjectPrx):

        def newUser(self, user, passwordHash, srvId, context=None):
            return _M_IceFlix.UserUpdates._op_newUser.invoke(self, ((user, passwordHash, srvId), context))

        def newUserAsync(self, user, passwordHash, srvId, context=None):
            return _M_IceFlix.UserUpdates._op_newUser.invokeAsync(self, ((user, passwordHash, srvId), context))

        def begin_newUser(self, user, passwordHash, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.UserUpdates._op_newUser.begin(self, ((user, passwordHash, srvId), _response, _ex, _sent, context))

        def end_newUser(self, _r):
            return _M_IceFlix.UserUpdates._op_newUser.end(self, _r)

        def newToken(self, user, userToken, srvId, context=None):
            return _M_IceFlix.UserUpdates._op_newToken.invoke(self, ((user, userToken, srvId), context))

        def newTokenAsync(self, user, userToken, srvId, context=None):
            return _M_IceFlix.UserUpdates._op_newToken.invokeAsync(self, ((user, userToken, srvId), context))

        def begin_newToken(self, user, userToken, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.UserUpdates._op_newToken.begin(self, ((user, userToken, srvId), _response, _ex, _sent, context))

        def end_newToken(self, _r):
            return _M_IceFlix.UserUpdates._op_newToken.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.UserUpdatesPrx.ice_checkedCast(proxy, '::IceFlix::UserUpdates', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.UserUpdatesPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::UserUpdates'
    _M_IceFlix._t_UserUpdatesPrx = IcePy.defineProxy('::IceFlix::UserUpdates', UserUpdatesPrx)

    _M_IceFlix.UserUpdatesPrx = UserUpdatesPrx
    del UserUpdatesPrx

    _M_IceFlix.UserUpdates = Ice.createTempClass()
    class UserUpdates(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::UserUpdates')

        def ice_id(self, current=None):
            return '::IceFlix::UserUpdates'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::UserUpdates'

        def newUser(self, user, passwordHash, srvId, current=None):
            raise NotImplementedError("servant method 'newUser' not implemented")

        def newToken(self, user, userToken, srvId, current=None):
            raise NotImplementedError("servant method 'newToken' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_UserUpdatesDisp)

        __repr__ = __str__

    _M_IceFlix._t_UserUpdatesDisp = IcePy.defineClass('::IceFlix::UserUpdates', UserUpdates, (), None, ())
    UserUpdates._ice_type = _M_IceFlix._t_UserUpdatesDisp

    UserUpdates._op_newUser = IcePy.Operation('newUser', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    UserUpdates._op_newToken = IcePy.Operation('newToken', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_IceFlix.UserUpdates = UserUpdates
    del UserUpdates

_M_IceFlix._t_Revocations = IcePy.defineValue('::IceFlix::Revocations', Ice.Value, -1, (), False, True, None, ())

if 'RevocationsPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.RevocationsPrx = Ice.createTempClass()
    class RevocationsPrx(Ice.ObjectPrx):

        def revokeToken(self, userToken, srvId, context=None):
            return _M_IceFlix.Revocations._op_revokeToken.invoke(self, ((userToken, srvId), context))

        def revokeTokenAsync(self, userToken, srvId, context=None):
            return _M_IceFlix.Revocations._op_revokeToken.invokeAsync(self, ((userToken, srvId), context))

        def begin_revokeToken(self, userToken, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Revocations._op_revokeToken.begin(self, ((userToken, srvId), _response, _ex, _sent, context))

        def end_revokeToken(self, _r):
            return _M_IceFlix.Revocations._op_revokeToken.end(self, _r)

        def revokeUser(self, user, srvId, context=None):
            return _M_IceFlix.Revocations._op_revokeUser.invoke(self, ((user, srvId), context))

        def revokeUserAsync(self, user, srvId, context=None):
            return _M_IceFlix.Revocations._op_revokeUser.invokeAsync(self, ((user, srvId), context))

        def begin_revokeUser(self, user, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Revocations._op_revokeUser.begin(self, ((user, srvId), _response, _ex, _sent, context))

        def end_revokeUser(self, _r):
            return _M_IceFlix.Revocations._op_revokeUser.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.RevocationsPrx.ice_checkedCast(proxy, '::IceFlix::Revocations', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.RevocationsPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Revocations'
    _M_IceFlix._t_RevocationsPrx = IcePy.defineProxy('::IceFlix::Revocations', RevocationsPrx)

    _M_IceFlix.RevocationsPrx = RevocationsPrx
    del RevocationsPrx

    _M_IceFlix.Revocations = Ice.createTempClass()
    class Revocations(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::Revocations')

        def ice_id(self, current=None):
            return '::IceFlix::Revocations'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Revocations'

        def revokeToken(self, userToken, srvId, current=None):
            raise NotImplementedError("servant method 'revokeToken' not implemented")

        def revokeUser(self, user, srvId, current=None):
            raise NotImplementedError("servant method 'revokeUser' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_RevocationsDisp)

        __repr__ = __str__

    _M_IceFlix._t_RevocationsDisp = IcePy.defineClass('::IceFlix::Revocations', Revocations, (), None, ())
    Revocations._ice_type = _M_IceFlix._t_RevocationsDisp

    Revocations._op_revokeToken = IcePy.Operation('revokeToken', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    Revocations._op_revokeUser = IcePy.Operation('revokeUser', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_IceFlix.Revocations = Revocations
    del Revocations

if '_t_AuthenticatorList' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_AuthenticatorList = IcePy.defineSequence('::IceFlix::AuthenticatorList', (), _M_IceFlix._t_AuthenticatorPrx)

if '_t_MediaCatalogList' not in _M_IceFlix.__dict__:
    _M_IceFlix._t_MediaCatalogList = IcePy.defineSequence('::IceFlix::MediaCatalogList', (), _M_IceFlix._t_MediaCatalogPrx)

if 'VolatileServices' not in _M_IceFlix.__dict__:
    _M_IceFlix.VolatileServices = Ice.createTempClass()
    class VolatileServices(object):
        def __init__(self, authenticators=None, mediaCatalogs=None):
            self.authenticators = authenticators
            self.mediaCatalogs = mediaCatalogs

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IceFlix.VolatileServices):
                return NotImplemented
            else:
                if self.authenticators != other.authenticators:
                    return False
                if self.mediaCatalogs != other.mediaCatalogs:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_VolatileServices)

        __repr__ = __str__

    _M_IceFlix._t_VolatileServices = IcePy.defineStruct('::IceFlix::VolatileServices', VolatileServices, (), (
        ('authenticators', (), _M_IceFlix._t_AuthenticatorList),
        ('mediaCatalogs', (), _M_IceFlix._t_MediaCatalogList)
    ))

    _M_IceFlix.VolatileServices = VolatileServices
    del VolatileServices

_M_IceFlix._t_Main = IcePy.defineValue('::IceFlix::Main', Ice.Value, -1, (), False, True, None, ())

if 'MainPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.MainPrx = Ice.createTempClass()
    class MainPrx(Ice.ObjectPrx):

        def getAuthenticator(self, context=None):
            return _M_IceFlix.Main._op_getAuthenticator.invoke(self, ((), context))

        def getAuthenticatorAsync(self, context=None):
            return _M_IceFlix.Main._op_getAuthenticator.invokeAsync(self, ((), context))

        def begin_getAuthenticator(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Main._op_getAuthenticator.begin(self, ((), _response, _ex, _sent, context))

        def end_getAuthenticator(self, _r):
            return _M_IceFlix.Main._op_getAuthenticator.end(self, _r)

        def getCatalog(self, context=None):
            return _M_IceFlix.Main._op_getCatalog.invoke(self, ((), context))

        def getCatalogAsync(self, context=None):
            return _M_IceFlix.Main._op_getCatalog.invokeAsync(self, ((), context))

        def begin_getCatalog(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Main._op_getCatalog.begin(self, ((), _response, _ex, _sent, context))

        def end_getCatalog(self, _r):
            return _M_IceFlix.Main._op_getCatalog.end(self, _r)

        def updateDB(self, currentServices, srvId, context=None):
            return _M_IceFlix.Main._op_updateDB.invoke(self, ((currentServices, srvId), context))

        def updateDBAsync(self, currentServices, srvId, context=None):
            return _M_IceFlix.Main._op_updateDB.invokeAsync(self, ((currentServices, srvId), context))

        def begin_updateDB(self, currentServices, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Main._op_updateDB.begin(self, ((currentServices, srvId), _response, _ex, _sent, context))

        def end_updateDB(self, _r):
            return _M_IceFlix.Main._op_updateDB.end(self, _r)

        def isAdmin(self, adminToken, context=None):
            return _M_IceFlix.Main._op_isAdmin.invoke(self, ((adminToken, ), context))

        def isAdminAsync(self, adminToken, context=None):
            return _M_IceFlix.Main._op_isAdmin.invokeAsync(self, ((adminToken, ), context))

        def begin_isAdmin(self, adminToken, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.Main._op_isAdmin.begin(self, ((adminToken, ), _response, _ex, _sent, context))

        def end_isAdmin(self, _r):
            return _M_IceFlix.Main._op_isAdmin.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.MainPrx.ice_checkedCast(proxy, '::IceFlix::Main', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.MainPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Main'
    _M_IceFlix._t_MainPrx = IcePy.defineProxy('::IceFlix::Main', MainPrx)

    _M_IceFlix.MainPrx = MainPrx
    del MainPrx

    _M_IceFlix.Main = Ice.createTempClass()
    class Main(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::Main')

        def ice_id(self, current=None):
            return '::IceFlix::Main'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::Main'

        def getAuthenticator(self, current=None):
            raise NotImplementedError("servant method 'getAuthenticator' not implemented")

        def getCatalog(self, current=None):
            raise NotImplementedError("servant method 'getCatalog' not implemented")

        def updateDB(self, currentServices, srvId, current=None):
            raise NotImplementedError("servant method 'updateDB' not implemented")

        def isAdmin(self, adminToken, current=None):
            raise NotImplementedError("servant method 'isAdmin' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_MainDisp)

        __repr__ = __str__

    _M_IceFlix._t_MainDisp = IcePy.defineClass('::IceFlix::Main', Main, (), None, ())
    Main._ice_type = _M_IceFlix._t_MainDisp

    Main._op_getAuthenticator = IcePy.Operation('getAuthenticator', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_IceFlix._t_AuthenticatorPrx, False, 0), (_M_IceFlix._t_TemporaryUnavailable,))
    Main._op_getCatalog = IcePy.Operation('getCatalog', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_IceFlix._t_MediaCatalogPrx, False, 0), (_M_IceFlix._t_TemporaryUnavailable,))
    Main._op_updateDB = IcePy.Operation('updateDB', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IceFlix._t_VolatileServices, False, 0), ((), IcePy._t_string, False, 0)), (), None, (_M_IceFlix._t_UnknownService,))
    Main._op_isAdmin = IcePy.Operation('isAdmin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_bool, False, 0), ())

    _M_IceFlix.Main = Main
    del Main

_M_IceFlix._t_ServiceAnnouncements = IcePy.defineValue('::IceFlix::ServiceAnnouncements', Ice.Value, -1, (), False, True, None, ())

if 'ServiceAnnouncementsPrx' not in _M_IceFlix.__dict__:
    _M_IceFlix.ServiceAnnouncementsPrx = Ice.createTempClass()
    class ServiceAnnouncementsPrx(Ice.ObjectPrx):

        def newService(self, service, srvId, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_newService.invoke(self, ((service, srvId), context))

        def newServiceAsync(self, service, srvId, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_newService.invokeAsync(self, ((service, srvId), context))

        def begin_newService(self, service, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_newService.begin(self, ((service, srvId), _response, _ex, _sent, context))

        def end_newService(self, _r):
            return _M_IceFlix.ServiceAnnouncements._op_newService.end(self, _r)

        def announce(self, service, srvId, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_announce.invoke(self, ((service, srvId), context))

        def announceAsync(self, service, srvId, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_announce.invokeAsync(self, ((service, srvId), context))

        def begin_announce(self, service, srvId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IceFlix.ServiceAnnouncements._op_announce.begin(self, ((service, srvId), _response, _ex, _sent, context))

        def end_announce(self, _r):
            return _M_IceFlix.ServiceAnnouncements._op_announce.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IceFlix.ServiceAnnouncementsPrx.ice_checkedCast(proxy, '::IceFlix::ServiceAnnouncements', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IceFlix.ServiceAnnouncementsPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IceFlix::ServiceAnnouncements'
    _M_IceFlix._t_ServiceAnnouncementsPrx = IcePy.defineProxy('::IceFlix::ServiceAnnouncements', ServiceAnnouncementsPrx)

    _M_IceFlix.ServiceAnnouncementsPrx = ServiceAnnouncementsPrx
    del ServiceAnnouncementsPrx

    _M_IceFlix.ServiceAnnouncements = Ice.createTempClass()
    class ServiceAnnouncements(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IceFlix::ServiceAnnouncements')

        def ice_id(self, current=None):
            return '::IceFlix::ServiceAnnouncements'

        @staticmethod
        def ice_staticId():
            return '::IceFlix::ServiceAnnouncements'

        def newService(self, service, srvId, current=None):
            raise NotImplementedError("servant method 'newService' not implemented")

        def announce(self, service, srvId, current=None):
            raise NotImplementedError("servant method 'announce' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IceFlix._t_ServiceAnnouncementsDisp)

        __repr__ = __str__

    _M_IceFlix._t_ServiceAnnouncementsDisp = IcePy.defineClass('::IceFlix::ServiceAnnouncements', ServiceAnnouncements, (), None, ())
    ServiceAnnouncements._ice_type = _M_IceFlix._t_ServiceAnnouncementsDisp

    ServiceAnnouncements._op_newService = IcePy.Operation('newService', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_ObjectPrx, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())
    ServiceAnnouncements._op_announce = IcePy.Operation('announce', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_ObjectPrx, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_IceFlix.ServiceAnnouncements = ServiceAnnouncements
    del ServiceAnnouncements

# End of module IceFlix
